### ISSUE TITLE
안녕하세요 질문이 있습니다.

### ISSUE THREAD

**Issue by elephantoid** [Ikalli/ReactFolio#3]
미디엄에서 react를 활용한 포트폴리오 만드는것을 보고 따라할려고 했으나 계속 local host에서 연결이 거부되는 이유는 무엇인지 여쭤봐도 될까요?
제가 node.js나 react는 처음이라 구글링을해봤지만 해당하는 내용을 찾기에 어려움이 있어서 여쭤봅니다
답변 달아주시면 감사하겠습니다.

**Comment by Ikalli** [comment]
Issue를 늦게 확인해서 죄송합니다...! 해결하셨나요??

**Comment by elephantoid** [comment]
아닙니다 !! 제가 능력이 부족해서 hexo를 이용한 블로그로 갈아탔습니다 감사합니다
